name: Build

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Format code
        run: yarn format

      - name: Lint code
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build code
        run: yarn build
